### PR TITLE
Multiple code cleanup for rules keys: squid:S2293, squid:S3027, squid…

### PR DESCRIPTION
**Pull request by elkfrawy-df**
This pull request is solving following Sonar rule:
 squid:S2293 - The operator ("<>") should be used.
 squid:S3027 - String function use should be optimized for single characters
 squid:S00122- “Statements should be on separate lines”. 

You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2293 https://dev.eclipse.org/sonar/rules/show/squid:S00122

Please let me know if you have any questions.
Ayman Elkfrawy

### CODE REVIEW

**Comment by androidmalin** [comment]
Good Job! Thank you!

**Comment by elkfrawy-df** [comment]
@androidmalin I fixed the conflicts with this branch

**Comment by elkfrawy-df** [comment]
@androidmalin I just wanted to let you know that these branches are not merged yet. Please let me know if there is a problem or you want me to do something.

**Comment by androidmalin** [comment]
@elkfrawy-df Thank you. Recently I am looking for a job.I forgot.

**Pull request merged**
